/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'apimentel' at '3/27/16 10:35 PM' with Gradle 2.7
 *
 * @author apimentel, @date 3/27/16 10:35 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
