package ws.ns.hystrix

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.cloud.netflix.turbine.amqp.EnableTurbineAmqp
import org.springframework.context.ApplicationContext
/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'apimentel' at '3/30/16 1:16 AM' with Gradle 2.7
 *
 * @author apimentel, @date 3/30/16 1:16 AM
 */
@SpringBootApplication
@EnableTurbineAmqp
class Library {
    public static void main(String[] args) {
        ApplicationContext ctx = SpringApplication.run(Library.class, args);
    }
}
