/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'apimentel' at '3/30/16 1:16 AM' with Gradle 2.7
 *
 * @author apimentel, @date 3/30/16 1:16 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
