package ws.ns.hystrix

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.context.ApplicationContext
import ws.ns.hystrix.data.RandomDomain
import ws.ns.hystrix.data.RandomRepository
import org.springframework.cloud.client.circuitbreaker.EnableCircuitBreaker


/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'apimentel' at '3/27/16 10:35 PM' with Gradle 2.7
 *
 * @author apimentel, @date 3/27/16 10:35 PM
 */
@SpringBootApplication
@EnableCircuitBreaker
class Library {
    public static void main(String[] args) {
        ApplicationContext ctx = SpringApplication.run(Library.class, args);
        RandomRepository randomRepository = ctx.getBean(RandomRepository)
        randomRepository.save(new RandomDomain(id: 1L, randomNumber: new Random().nextInt(1000), randomString: UUID.randomUUID().toString()))
    }
}
