/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'apimentel' at '3/27/16 10:35 PM' with Gradle 2.7
 *
 * @author apimentel, @date 3/27/16 10:35 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{

}
